# Generated by Django 3.2.6 on 2021-08-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0003_pricehistory_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='temp',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
