# Generated by Django 3.2.6 on 2021-08-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0004_auto_20210819_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='temp',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
